name: easy2hard-vllm
channels:
  - nvidia/label/cuda-12.8.1
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda=12.8.1=0
  - cuda-cccl_linux-64=12.8.90=h06a4308_1
  - cuda-command-line-tools=12.8.1=0
  - cuda-compiler=12.8.1=0
  - cuda-crt-dev_linux-64=12.8.93=h06a4308_3
  - cuda-crt-tools=12.8.93=h06a4308_3
  - cuda-cudart=12.8.90=hbdd6827_0
  - cuda-cudart-dev=12.8.90=hbdd6827_0
  - cuda-cudart-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart-static=12.8.90=hbdd6827_0
  - cuda-cudart-static_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-cuobjdump=12.8.90=0
  - cuda-cupti=12.8.90=hbdd6827_1
  - cuda-cupti-dev=12.8.90=hbdd6827_1
  - cuda-cuxxfilt=12.8.90=0
  - cuda-driver-dev=12.8.90=hbdd6827_0
  - cuda-driver-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-gdb=12.8.90=0
  - cuda-libraries=12.8.1=0
  - cuda-libraries-dev=12.8.1=0
  - cuda-nsight=12.8.90=0
  - cuda-nvcc=12.8.93=h02f8991_2
  - cuda-nvcc-dev_linux-64=12.8.93=he2511ca_3
  - cuda-nvcc-impl=12.8.93=hd1a145a_3
  - cuda-nvcc-tools=12.8.93=hbdd6827_3
  - cuda-nvcc_linux-64=12.8.93=h2f703a9_2
  - cuda-nvdisasm=12.8.90=0
  - cuda-nvml-dev=12.8.90=0
  - cuda-nvprof=12.8.90=0
  - cuda-nvprune=12.8.90=0
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-nvrtc-dev=12.8.93=hbdd6827_1
  - cuda-nvtx=12.8.90=0
  - cuda-nvvm-dev_linux-64=12.8.93=h06a4308_3
  - cuda-nvvm-impl=12.8.93=hbdd6827_3
  - cuda-nvvm-tools=12.8.93=hbdd6827_3
  - cuda-nvvp=12.8.93=0
  - cuda-opencl=12.8.90=hb6f8877_1
  - cuda-opencl-dev=12.8.90=hbdd6827_1
  - cuda-profiler-api=12.8.90=0
  - cuda-runtime=12.8.1=0
  - cuda-sanitizer-api=12.8.93=0
  - cuda-toolkit=12.8.1=0
  - cuda-tools=12.8.1=0
  - cuda-version=12.8=h30beaf8_3
  - cuda-visual-tools=12.8.1=0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.14=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.13.1.3=0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kernel-headers_linux-64=4.18.0=h528b178_0
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.8.4.1=hbdd6827_1
  - libcublas-dev=12.8.4.1=hbdd6827_1
  - libcufft=11.3.3.83=0
  - libcufft-dev=11.3.3.83=0
  - libcufile=1.13.1.3=0
  - libcufile-dev=1.13.1.3=0
  - libcurand=10.3.9.90=0
  - libcurand-dev=10.3.9.90=0
  - libcusolver=11.7.3.90=0
  - libcusolver-dev=11.7.3.90=0
  - libcusparse=12.5.8.93=hbdd6827_1
  - libcusparse-dev=12.5.8.93=hbdd6827_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.1.0=h69a702a_2
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - libnpp=12.3.3.100=hbdd6827_1
  - libnpp-dev=12.3.3.100=hbdd6827_1
  - libnvfatbin=12.8.90=hbdd6827_1
  - libnvfatbin-dev=12.8.90=hbdd6827_1
  - libnvjitlink=12.8.93=hbdd6827_1
  - libnvjitlink-dev=12.8.93=hbdd6827_1
  - libnvjpeg=12.3.5.92=0
  - libnvjpeg-dev=12.3.5.92=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nsight-compute=2025.1.1.2=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openssl=3.5.0=h7b32b05_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311h9ecbd09_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.11=2_cp311
  - pyzmq=26.4.0=py311h7deb3e3_0
  - readline=8.2=h5eee18b_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.28=h528b178_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py311h9ecbd09_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.11.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astor==0.8.1
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.45.5
      - blake3==1.0.7
      - bleach==6.2.0
      - build==1.3.0
      - cachetools==6.2.0
      - cbor2==5.7.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - colorama==0.4.6
      - compressed-tensors==0.11.0
      - contourpy==1.3.2
      - cupy-cuda12x==13.6.0
      - cut-cross-entropy==25.1.1
      - cycler==0.12.1
      - dataproperty==1.1.0
      - datasets==3.6.0
      - deepspeed==0.16.9
      - defusedxml==0.7.1
      - depyf==0.19.0
      - diffusers==0.33.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.1
      - email-validator==2.3.0
      - evaluate==0.4.3
      - fastapi==0.118.0
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.2.1
      - fastjsonschema==2.21.1
      - fastrlock==0.8.3
      - filelock==3.18.0
      - fonttools==4.58.0
      - fqdn==1.5.1
      - frozendict==2.4.6
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.10
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - immutabledict==4.2.1
      - interegular==0.3.3
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jiter==0.11.0
      - joblib==1.5.0
      - json5==0.12.0
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - langdetect==1.0.9
      - lark==1.2.2
      - latex2sympy2-extended==1.10.2
      - liger-kernel==0.5.10
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-eval==0.4.8
      - lm-format-enforcer==0.11.3
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - math-verify==0.8.0
      - matplotlib==3.10.3
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mistune==3.1.3
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numexpr==2.10.2
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.1.0
      - openai-harmony==0.0.4
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.4.0
      - ordered-set==4.1.0
      - outlines-core==0.2.11
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - partial-json-parser==0.2.1.1.post6
      - pathvalidate==3.2.3
      - peft==0.15.2
      - pillow==11.2.1
      - portalocker==3.1.1
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.1
      - protobuf==3.20.3
      - py-cpuinfo==9.0.0
      - py-irt==0.6.5
      - pyarrow==20.0.0
      - pybase64==1.4.2
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pyparsing==3.2.3
      - pyproject-hooks==1.2.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytablewriter==1.2.1
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.49.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rich-toolkit==0.15.1
      - rignore==0.6.4
      - rouge-score==0.1.2
      - rpds-py==0.24.0
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - setuptools==79.0.1
      - setuptools-scm==9.2.0
      - shellingham==1.5.4
      - shtab==1.7.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==1.0.0
      - sqlitedict==2.1.0
      - starlette==0.48.0
      - sympy==1.14.0
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - transformers==4.56.2
      - triton==3.4.0
      - trl==0.15.2
      - typeguard==4.4.2
      - typepy==1.3.4
      - typer==0.19.2
      - types-python-dateutil==2.9.0.20241206
      - typing-inspection==0.4.0
      - tyro==0.9.19
      - tzdata==2025.2
      - umap==0.1.1
      - unsloth==2025.5.3
      - unsloth-zoo==2025.5.5
      - uri-template==1.3.0
      - urllib3==2.4.0
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - vllm==0.10.2
      - wandb==0.19.11
      - watchfiles==1.1.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
      - word2number==1.1
      - xformers==0.0.32.post1
      - xgrammar==0.1.23
      - xxhash==3.5.0
      - yarl==1.20.0
      - zstandard==0.23.0
prefix: /users/ykordi/data/ykordi/x86-envs/anaconda3/envs/easy2hard-vllm
